ragflow:
  host: 0.0.0.0
  http_port: 9380
admin:
  host: 0.0.0.0
  http_port: 9381
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'infini_rag_flow'
  host: 'mysql'
  port: 3306
  max_connections: 900
  stale_timeout: 300
  max_allowed_packet: 1073741824
minio:
  user: 'rag_flow'
  password: 'infini_rag_flow'
  host: 'minio:9000'
es:
  hosts: 'http://es01:9200'
  username: 'elastic'
  password: 'infini_rag_flow'
os:
  hosts: 'http://opensearch01:9201'
  username: 'admin'
  password: 'infini_rag_flow_OS_01'
infinity:
  uri: 'infinity:23817'
  db_name: 'default_db'
redis:
  db: 1
  password: 'infini_rag_flow'
  host: 'redis:6379'

